version: '2.4'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "7117:7117"
    cpus: 1
    pids_limit: 64
    mem_limit: 512m
    volumes:
      - machines:/machines
  cleaner:
    image: c4tbuts4d/dedcleaner:latest
    restart: unless-stopped
    volumes:
      - machines:/data
    environment:
      - DELETE_AFTER=30m
      - SLEEP=30m
      - DIRS=/data

volumes:
  machines:
