services:
  mongodb:
    image: mongo:8.0.0
    volumes:
      - dbdata:/data/db
    restart: unless-stopped
    pids_limit: 512
    mem_limit: 512m
    cpus: 1

  search:
    build: search
    volumes:
      - searchdata:/data
    environment:
      - "INDEX_FILE=/data/bleve.index"
    restart: unless-stopped
    pids_limit: 512
    mem_limit: 512m
    cpus: 1

  api:
    build: api
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - mongodb
      - search
    pids_limit: 512
    mem_limit: 1g
    cpus: 2

volumes:
  dbdata:
  searchdata: